In [1]:
import  pandas as pd
import numpy as np

df = pd.read_csv('netflix1.csv')
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [3]:
df.shape
print(f"The number of rows in the data are {df.shape[0]} and number of columns are {df.shape[1]}")

The number of rows in the data are 8790 and number of columns are 10

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

In [34]:
df.columns
df.drop(columns="Country",inplace=True)
df.head()   #column of date added removed

,Show_id,Type,Title,Director,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,1993,125 min,"Dramas, Independent Movies, International Movies"

In [35]:
new_column=[]
for i in df.columns:
    new_column.append(i.capitalize())

df.columns=new_column
df.columns  #to start the first name with capital letter

Index(['Show_id', 'Type', 'Title', 'Director', 'Release_year', 'Duration',
       'Listed_in'],
      dtype='str')

In [36]:
# to see some duplicate
df.duplicated().sum()   # we have no duplicates in our data

np.int64(0)

In [37]:
#to drop duplicates
df.drop_duplicates(inplace=True)

In [38]:
# to drop nan values,first checking if there are nan values
df.isna().sum()

Show_id         0
Type            0
Title           0
Director        0
Release_year    0
Duration        0
Listed_in       0
dtype: int64

In [ ]:
df.head()
df['Show_id'].unique()
df['Show_id'].apply(lambda x:x.split('s')[1])
  #we can see that the show id is string dtype we should convert it into int

<StringArray>
[   '1',    '3',    '6',   '14',    '8',    '9',   '10',  '939',   '13',
  '940',
 ...
 '8759', '8776', '8781', '8785', '8796', '8797', '8798', '8801', '8784',
 '8786']
Length: 8790, dtype: str

In [ ]:
df.head()  
df['Type']=df['Type'].apply(lambda x:x.replace('Movie','Film'))
df.head()

,Show_id,Type,Title,Director,Release_year,Duration,Listed_in
0,1,Film,Dick Johnson Is Dead,Kirsten Johnson,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Film,Confessions of an Invisible Girl,Bruno Garotti,2021,91 min,"Children & Family Movies, Comedies"
4,8,Film,Sankofa,Haile Gerima,1993,125 min,"Dramas, Independent Movies, International Movies"

In [ ]:
data = df['Type'].value_counts()
data